#pragma once

#define HIDROSMART_WIFI_SSID "CAMBIA_WIFI_SSID"
#define HIDROSMART_WIFI_PASSWORD "CAMBIA_WIFI_PASSWORD"
#define HIDROSMART_MQTT_HOST "192.168.1.10"
#define HIDROSMART_MQTT_PORT 1883
#define HIDROSMART_DEVICE_CODE "ESP32-001"
#define HIDROSMART_MQTT_USERNAME ""
#define HIDROSMART_MQTT_PASSWORD ""
#define HIDROSMART_FLOW_PIN 27
#define HIDROSMART_PULSE_LITERS 0.04f
