-- Las funciones SECURITY DEFINER no quedan invocables por PUBLIC.
REVOKE ALL ON FUNCTION public.fn_update_updated_at() FROM PUBLIC;
REVOKE ALL ON FUNCTION user_account.fn_app_current_user_id() FROM PUBLIC;
REVOKE ALL ON FUNCTION user_account.fn_app_has_permission(VARCHAR) FROM PUBLIC;
REVOKE ALL ON FUNCTION user_account.fn_user_has_permission(UUID, VARCHAR) FROM PUBLIC;
REVOKE ALL ON FUNCTION home.fn_is_home_member(UUID, UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION home.fn_is_home_owner(UUID, UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION device.fn_can_access_device(UUID, UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION device.fn_can_manage_device(UUID, UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION home.fn_is_vacation_active(UUID, DATE) FROM PUBLIC;
REVOKE ALL ON FUNCTION alert_rate.fn_check_threshold(DECIMAL, UUID, DATE) FROM PUBLIC;
REVOKE ALL ON FUNCTION alert_rate.fn_is_leak_detected(UUID, TIMESTAMPTZ, INTEGER) FROM PUBLIC;
REVOKE ALL ON FUNCTION analytics_support.fn_get_goal_progress(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION consumption.fn_calculate_consumption(UUID, DATE, DATE) FROM PUBLIC;
REVOKE ALL ON FUNCTION consumption.fn_calculate_cost(DECIMAL, UUID, DATE) FROM PUBLIC;
REVOKE ALL ON FUNCTION consumption.fn_get_daily_consumption(UUID, DATE) FROM PUBLIC;
REVOKE ALL ON FUNCTION consumption.fn_get_monthly_consumption(UUID, INTEGER, INTEGER) FROM PUBLIC;
REVOKE ALL ON FUNCTION consumption.fn_calculate_period_cost(UUID, DATE, DATE) FROM PUBLIC;
REVOKE ALL ON FUNCTION consumption.fn_after_reading_insert() FROM PUBLIC;
REVOKE ALL ON FUNCTION user_account.fn_audit_user_account() FROM PUBLIC;
REVOKE ALL ON FUNCTION device.fn_track_device_status_change() FROM PUBLIC;
REVOKE ALL ON FUNCTION home.fn_assert_home_has_owner() FROM PUBLIC;
REVOKE ALL ON FUNCTION home.fn_add_home_member(UUID, VARCHAR, VARCHAR) FROM PUBLIC;
REVOKE ALL ON FUNCTION home.fn_change_home_member_role(UUID, UUID, VARCHAR) FROM PUBLIC;
REVOKE ALL ON FUNCTION home.fn_remove_home_member(UUID, UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION home.fn_request_home_membership(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION home.fn_answer_home_membership_request(UUID, VARCHAR) FROM PUBLIC;
REVOKE ALL ON PROCEDURE analytics_support.prc_refresh_materialized_views() FROM PUBLIC;

-- Funciones que el rol de aplicación usa directamente o desde RLS.
GRANT EXECUTE ON FUNCTION user_account.fn_app_current_user_id() TO hidro_smart_app;
GRANT EXECUTE ON FUNCTION user_account.fn_app_has_permission(VARCHAR) TO hidro_smart_app;
GRANT EXECUTE ON FUNCTION user_account.fn_user_has_permission(UUID, VARCHAR) TO hidro_smart_app;
GRANT EXECUTE ON FUNCTION home.fn_is_home_member(UUID, UUID) TO hidro_smart_app;
GRANT EXECUTE ON FUNCTION home.fn_is_home_owner(UUID, UUID) TO hidro_smart_app;
GRANT EXECUTE ON FUNCTION home.fn_add_home_member(UUID, VARCHAR, VARCHAR) TO hidro_smart_app;
GRANT EXECUTE ON FUNCTION home.fn_change_home_member_role(UUID, UUID, VARCHAR) TO hidro_smart_app;
GRANT EXECUTE ON FUNCTION home.fn_remove_home_member(UUID, UUID) TO hidro_smart_app;
GRANT EXECUTE ON FUNCTION home.fn_request_home_membership(UUID) TO hidro_smart_app;
GRANT EXECUTE ON FUNCTION home.fn_answer_home_membership_request(UUID, VARCHAR) TO hidro_smart_app;
GRANT EXECUTE ON FUNCTION device.fn_can_access_device(UUID, UUID) TO hidro_smart_app;
GRANT EXECUTE ON FUNCTION device.fn_can_manage_device(UUID, UUID) TO hidro_smart_app;
GRANT EXECUTE ON FUNCTION home.fn_is_vacation_active(UUID, DATE) TO hidro_smart_app;
GRANT EXECUTE ON FUNCTION consumption.fn_calculate_consumption(UUID, DATE, DATE) TO hidro_smart_app;
GRANT EXECUTE ON FUNCTION consumption.fn_calculate_cost(DECIMAL, UUID, DATE) TO hidro_smart_app;
GRANT EXECUTE ON FUNCTION consumption.fn_get_daily_consumption(UUID, DATE) TO hidro_smart_app;
GRANT EXECUTE ON FUNCTION consumption.fn_get_monthly_consumption(UUID, INTEGER, INTEGER) TO hidro_smart_app;
GRANT EXECUTE ON FUNCTION consumption.fn_calculate_period_cost(UUID, DATE, DATE) TO hidro_smart_app;
GRANT EXECUTE ON FUNCTION alert_rate.fn_is_leak_detected(UUID, TIMESTAMPTZ, INTEGER) TO hidro_smart_app;
GRANT EXECUTE ON FUNCTION analytics_support.fn_get_goal_progress(UUID) TO hidro_smart_app;
GRANT EXECUTE ON PROCEDURE analytics_support.prc_refresh_materialized_views() TO hidro_smart_app;
