REVOKE ALL ON FUNCTION user_account.fn_list_audit_logs(VARCHAR, VARCHAR, TIMESTAMPTZ, TIMESTAMPTZ, INTEGER, INTEGER) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION user_account.fn_list_audit_logs(VARCHAR, VARCHAR, TIMESTAMPTZ, TIMESTAMPTZ, INTEGER, INTEGER) TO hidro_smart_app;
