GRANT EXECUTE ON FUNCTION device.fn_ingest_sensor_reading(
    VARCHAR, VARCHAR, NUMERIC, TIMESTAMPTZ, NUMERIC, NUMERIC, INTEGER,
    NUMERIC, INTEGER, INTEGER, INTEGER, NUMERIC, NUMERIC
) TO hidro_smart_ingest;
