GRANT EXECUTE ON FUNCTION public.fn_update_updated_at() TO PUBLIC;
GRANT EXECUTE ON FUNCTION user_account.fn_app_current_user_id() TO PUBLIC;
GRANT EXECUTE ON FUNCTION user_account.fn_app_has_permission(VARCHAR) TO PUBLIC;
GRANT EXECUTE ON FUNCTION user_account.fn_user_has_permission(UUID, VARCHAR) TO PUBLIC;
GRANT EXECUTE ON FUNCTION home.fn_is_home_member(UUID, UUID) TO PUBLIC;
GRANT EXECUTE ON FUNCTION home.fn_is_home_owner(UUID, UUID) TO PUBLIC;
GRANT EXECUTE ON FUNCTION device.fn_can_access_device(UUID, UUID) TO PUBLIC;
GRANT EXECUTE ON FUNCTION device.fn_can_manage_device(UUID, UUID) TO PUBLIC;
GRANT EXECUTE ON FUNCTION home.fn_is_vacation_active(UUID, DATE) TO PUBLIC;
GRANT EXECUTE ON FUNCTION alert_rate.fn_check_threshold(DECIMAL, UUID, DATE) TO PUBLIC;
GRANT EXECUTE ON FUNCTION alert_rate.fn_is_leak_detected(UUID, TIMESTAMPTZ, INTEGER) TO PUBLIC;
GRANT EXECUTE ON FUNCTION analytics_support.fn_get_goal_progress(UUID) TO PUBLIC;
GRANT EXECUTE ON FUNCTION consumption.fn_calculate_consumption(UUID, DATE, DATE) TO PUBLIC;
GRANT EXECUTE ON FUNCTION consumption.fn_calculate_cost(DECIMAL, UUID, DATE) TO PUBLIC;
GRANT EXECUTE ON FUNCTION consumption.fn_get_daily_consumption(UUID, DATE) TO PUBLIC;
GRANT EXECUTE ON FUNCTION consumption.fn_get_monthly_consumption(UUID, INTEGER, INTEGER) TO PUBLIC;
GRANT EXECUTE ON FUNCTION consumption.fn_calculate_period_cost(UUID, DATE, DATE) TO PUBLIC;
GRANT EXECUTE ON FUNCTION consumption.fn_after_reading_insert() TO PUBLIC;
GRANT EXECUTE ON FUNCTION user_account.fn_audit_user_account() TO PUBLIC;
GRANT EXECUTE ON FUNCTION device.fn_track_device_status_change() TO PUBLIC;
GRANT EXECUTE ON FUNCTION home.fn_assert_home_has_owner() TO PUBLIC;
REVOKE EXECUTE ON PROCEDURE analytics_support.prc_refresh_materialized_views() FROM hidro_smart_app;
GRANT EXECUTE ON PROCEDURE analytics_support.prc_refresh_materialized_views() TO PUBLIC;