REVOKE EXECUTE ON FUNCTION device.fn_register_device_with_provisioning(VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, DECIMAL) FROM hidro_smart_app;
REVOKE EXECUTE ON FUNCTION device.fn_update_device_provisioning(UUID, VARCHAR, VARCHAR, VARCHAR) FROM hidro_smart_app;
REVOKE EXECUTE ON FUNCTION device.fn_record_device_status(VARCHAR, VARCHAR, TIMESTAMPTZ, VARCHAR, INTEGER, INTEGER, INTEGER, VARCHAR, VARCHAR, VARCHAR) FROM hidro_smart_app;
REVOKE EXECUTE ON FUNCTION device.fn_ingest_sensor_reading(VARCHAR, VARCHAR, NUMERIC, TIMESTAMPTZ, NUMERIC, NUMERIC, INTEGER, NUMERIC, INTEGER, INTEGER, INTEGER, NUMERIC, NUMERIC, VARCHAR) FROM hidro_smart_ingest;
